### ISSUE TITLE
Help deploying Ionic 2 app as a PWA

### ISSUE THREAD

**Issue by sk-aravind** [jgw96/Ionic2-Hacker-News#1]
Awesome PWA! I'm having some troubles deploying my ionic 2 app as a PWA, would you happen to have any useful guides or helpful links I could reference? Thanks alot, any help would be greatly appreciated :)

**Comment by jgw96** [comment]
Hello @sk-aravind, thanks for the kind words! Would you mind letting me know what kind of issues you are having specifically?

**Comment by sk-aravind** [comment]
I was wondering if there is a way to hide the bottom bar of safari (http://i.stack.imgur.com/s4lev.png) when scrolling down and minimize the navigation bar. Like how it works natively on a normal mobile site. From what I have understood, this happens because the body takes up 100% of the page, the browser thinks there is no where left to scroll and displays the bottom and top navigation bar.

**Comment by jgw96** [comment]
Hello @sk-aravind ! There is an issue open about this on the ionic repo and is something that we will be looking into. Thanks!
